// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: apps/personal-finance/adapter/finance.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FinanceType int32

const (
	FinanceType_FINANCE_TYPE_UNSPECIFIED FinanceType = 0
	FinanceType_FINANCE_TYPE_INCOME      FinanceType = 1
	FinanceType_FINANCE_TYPE_EXPENSE     FinanceType = 2
)

// Enum value maps for FinanceType.
var (
	FinanceType_name = map[int32]string{
		0: "FINANCE_TYPE_UNSPECIFIED",
		1: "FINANCE_TYPE_INCOME",
		2: "FINANCE_TYPE_EXPENSE",
	}
	FinanceType_value = map[string]int32{
		"FINANCE_TYPE_UNSPECIFIED": 0,
		"FINANCE_TYPE_INCOME":      1,
		"FINANCE_TYPE_EXPENSE":     2,
	}
)

func (x FinanceType) Enum() *FinanceType {
	p := new(FinanceType)
	*p = x
	return p
}

func (x FinanceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FinanceType) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_personal_finance_adapter_finance_proto_enumTypes[0].Descriptor()
}

func (FinanceType) Type() protoreflect.EnumType {
	return &file_apps_personal_finance_adapter_finance_proto_enumTypes[0]
}

func (x FinanceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FinanceType.Descriptor instead.
func (FinanceType) EnumDescriptor() ([]byte, []int) {
	return file_apps_personal_finance_adapter_finance_proto_rawDescGZIP(), []int{0}
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          FinanceType            `protobuf:"varint,4,opt,name=type,proto3,enum=personal.finance.FinanceType" json:"type,omitempty"`
	SortOrder     int32                  `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_apps_personal_finance_adapter_finance_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetType() FinanceType {
	if x != nil {
		return x.Type
	}
	return FinanceType_FINANCE_TYPE_UNSPECIFIED
}

func (x *Category) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Category) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Category) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CategoryId    int64                  `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Type          FinanceType            `protobuf:"varint,4,opt,name=type,proto3,enum=personal.finance.FinanceType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Amount        float64                `protobuf:"fixed64,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Date          string                 `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`
	Note          string                 `protobuf:"bytes,8,opt,name=note,proto3" json:"note,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_apps_personal_finance_adapter_finance_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transaction) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Transaction) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Transaction) GetType() FinanceType {
	if x != nil {
		return x.Type
	}
	return FinanceType_FINANCE_TYPE_UNSPECIFIED
}

func (x *Transaction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Transaction) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Transaction) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Transaction) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_apps_personal_finance_adapter_finance_proto_rawDescGZIP(), []int{2}
}

func (x *ListCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          FinanceType            `protobuf:"varint,2,opt,name=type,proto3,enum=personal.finance.FinanceType" json:"type,omitempty"`
	SortOrder     int32                  `protobuf:"varint,3,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_finance_adapter_finance_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCategoryRequest) GetType() FinanceType {
	if x != nil {
		return x.Type
	}
	return FinanceType_FINANCE_TYPE_UNSPECIFIED
}

func (x *CreateCategoryRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type UpdateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          FinanceType            `protobuf:"varint,3,opt,name=type,proto3,enum=personal.finance.FinanceType" json:"type,omitempty"`
	SortOrder     int32                  `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryRequest) Reset() {
	*x = UpdateCategoryRequest{}
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryRequest) ProtoMessage() {}

func (x *UpdateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_finance_adapter_finance_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCategoryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCategoryRequest) GetType() FinanceType {
	if x != nil {
		return x.Type
	}
	return FinanceType_FINANCE_TYPE_UNSPECIFIED
}

func (x *UpdateCategoryRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type DeleteCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryRequest) Reset() {
	*x = DeleteCategoryRequest{}
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryRequest) ProtoMessage() {}

func (x *DeleteCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_finance_adapter_finance_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCategoryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	CategoryId    int64                  `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsRequest) Reset() {
	*x = ListTransactionsRequest{}
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRequest) ProtoMessage() {}

func (x *ListTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_finance_adapter_finance_proto_rawDescGZIP(), []int{6}
}

func (x *ListTransactionsRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ListTransactionsRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *ListTransactionsRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ListTransactionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTransactionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_apps_personal_finance_adapter_finance_proto_rawDescGZIP(), []int{7}
}

func (x *ListTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ListTransactionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Type          FinanceType            `protobuf:"varint,2,opt,name=type,proto3,enum=personal.finance.FinanceType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Date          string                 `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Note          string                 `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_finance_adapter_finance_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTransactionRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateTransactionRequest) GetType() FinanceType {
	if x != nil {
		return x.Type
	}
	return FinanceType_FINANCE_TYPE_UNSPECIFIED
}

func (x *CreateTransactionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CreateTransactionRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type UpdateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId    int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Type          FinanceType            `protobuf:"varint,3,opt,name=type,proto3,enum=personal.finance.FinanceType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Amount        float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Date          string                 `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`
	Note          string                 `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTransactionRequest) Reset() {
	*x = UpdateTransactionRequest{}
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionRequest) ProtoMessage() {}

func (x *UpdateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionRequest.ProtoReflect.Descriptor instead.
func (*UpdateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_finance_adapter_finance_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTransactionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTransactionRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *UpdateTransactionRequest) GetType() FinanceType {
	if x != nil {
		return x.Type
	}
	return FinanceType_FINANCE_TYPE_UNSPECIFIED
}

func (x *UpdateTransactionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateTransactionRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *UpdateTransactionRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type DeleteTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransactionRequest) Reset() {
	*x = DeleteTransactionRequest{}
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionRequest) ProtoMessage() {}

func (x *DeleteTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionRequest.ProtoReflect.Descriptor instead.
func (*DeleteTransactionRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_finance_adapter_finance_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTransactionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMonthlySummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonthlySummaryRequest) Reset() {
	*x = GetMonthlySummaryRequest{}
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonthlySummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthlySummaryRequest) ProtoMessage() {}

func (x *GetMonthlySummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthlySummaryRequest.ProtoReflect.Descriptor instead.
func (*GetMonthlySummaryRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_finance_adapter_finance_proto_rawDescGZIP(), []int{11}
}

func (x *GetMonthlySummaryRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetMonthlySummaryRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type CategorySummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName  string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategorySummary) Reset() {
	*x = CategorySummary{}
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategorySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategorySummary) ProtoMessage() {}

func (x *CategorySummary) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategorySummary.ProtoReflect.Descriptor instead.
func (*CategorySummary) Descriptor() ([]byte, []int) {
	return file_apps_personal_finance_adapter_finance_proto_rawDescGZIP(), []int{12}
}

func (x *CategorySummary) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CategorySummary) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *CategorySummary) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type MonthlySummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalIncome       float64                `protobuf:"fixed64,1,opt,name=total_income,json=totalIncome,proto3" json:"total_income,omitempty"`
	TotalExpense      float64                `protobuf:"fixed64,2,opt,name=total_expense,json=totalExpense,proto3" json:"total_expense,omitempty"`
	NetBalance        float64                `protobuf:"fixed64,3,opt,name=net_balance,json=netBalance,proto3" json:"net_balance,omitempty"`
	CategorySummaries []*CategorySummary     `protobuf:"bytes,4,rep,name=category_summaries,json=categorySummaries,proto3" json:"category_summaries,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MonthlySummary) Reset() {
	*x = MonthlySummary{}
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlySummary) ProtoMessage() {}

func (x *MonthlySummary) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_finance_adapter_finance_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlySummary.ProtoReflect.Descriptor instead.
func (*MonthlySummary) Descriptor() ([]byte, []int) {
	return file_apps_personal_finance_adapter_finance_proto_rawDescGZIP(), []int{13}
}

func (x *MonthlySummary) GetTotalIncome() float64 {
	if x != nil {
		return x.TotalIncome
	}
	return 0
}

func (x *MonthlySummary) GetTotalExpense() float64 {
	if x != nil {
		return x.TotalExpense
	}
	return 0
}

func (x *MonthlySummary) GetNetBalance() float64 {
	if x != nil {
		return x.NetBalance
	}
	return 0
}

func (x *MonthlySummary) GetCategorySummaries() []*CategorySummary {
	if x != nil {
		return x.CategorySummaries
	}
	return nil
}

var File_apps_personal_finance_adapter_finance_proto protoreflect.FileDescriptor

const file_apps_personal_finance_adapter_finance_proto_rawDesc = "" +
	"\n" +
	"+apps/personal-finance/adapter/finance.proto\x12\x10personal.finance\x1a\x1bgoogle/protobuf/empty.proto\"\xdd\x01\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x121\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1d.personal.finance.FinanceTypeR\x04type\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x05R\tsortOrder\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"\xa2\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x03R\n" +
	"categoryId\x121\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1d.personal.finance.FinanceTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x01R\x06amount\x12\x12\n" +
	"\x04date\x18\a \x01(\tR\x04date\x12\x12\n" +
	"\x04note\x18\b \x01(\tR\x04note\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\"T\n" +
	"\x16ListCategoriesResponse\x12:\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x1a.personal.finance.CategoryR\n" +
	"categories\"}\n" +
	"\x15CreateCategoryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.personal.finance.FinanceTypeR\x04type\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\x05R\tsortOrder\"\x8d\x01\n" +
	"\x15UpdateCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x121\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1d.personal.finance.FinanceTypeR\x04type\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05R\tsortOrder\"'\n" +
	"\x15DeleteCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x95\x01\n" +
	"\x17ListTransactionsRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"s\n" +
	"\x18ListTransactionsResponse\x12A\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1d.personal.finance.TransactionR\ftransactions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xc2\x01\n" +
	"\x18CreateTransactionRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\x121\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.personal.finance.FinanceTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x12\n" +
	"\x04date\x18\x05 \x01(\tR\x04date\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\"\xd2\x01\n" +
	"\x18UpdateTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\x121\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1d.personal.finance.FinanceTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x12\n" +
	"\x04date\x18\x06 \x01(\tR\x04date\x12\x12\n" +
	"\x04note\x18\a \x01(\tR\x04note\"*\n" +
	"\x18DeleteTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"D\n" +
	"\x18GetMonthlySummaryRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\"z\n" +
	"\x0fCategorySummary\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x01R\vtotalAmount\"\xcb\x01\n" +
	"\x0eMonthlySummary\x12!\n" +
	"\ftotal_income\x18\x01 \x01(\x01R\vtotalIncome\x12#\n" +
	"\rtotal_expense\x18\x02 \x01(\x01R\ftotalExpense\x12\x1f\n" +
	"\vnet_balance\x18\x03 \x01(\x01R\n" +
	"netBalance\x12P\n" +
	"\x12category_summaries\x18\x04 \x03(\v2!.personal.finance.CategorySummaryR\x11categorySummaries*^\n" +
	"\vFinanceType\x12\x1c\n" +
	"\x18FINANCE_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13FINANCE_TYPE_INCOME\x10\x01\x12\x18\n" +
	"\x14FINANCE_TYPE_EXPENSE\x10\x022\xc5\x06\n" +
	"\aFinance\x12R\n" +
	"\x0eListCategories\x12\x16.google.protobuf.Empty\x1a(.personal.finance.ListCategoriesResponse\x12U\n" +
	"\x0eCreateCategory\x12'.personal.finance.CreateCategoryRequest\x1a\x1a.personal.finance.Category\x12U\n" +
	"\x0eUpdateCategory\x12'.personal.finance.UpdateCategoryRequest\x1a\x1a.personal.finance.Category\x12Q\n" +
	"\x0eDeleteCategory\x12'.personal.finance.DeleteCategoryRequest\x1a\x16.google.protobuf.Empty\x12i\n" +
	"\x10ListTransactions\x12).personal.finance.ListTransactionsRequest\x1a*.personal.finance.ListTransactionsResponse\x12^\n" +
	"\x11CreateTransaction\x12*.personal.finance.CreateTransactionRequest\x1a\x1d.personal.finance.Transaction\x12^\n" +
	"\x11UpdateTransaction\x12*.personal.finance.UpdateTransactionRequest\x1a\x1d.personal.finance.Transaction\x12W\n" +
	"\x11DeleteTransaction\x12*.personal.finance.DeleteTransactionRequest\x1a\x16.google.protobuf.Empty\x12a\n" +
	"\x11GetMonthlySummary\x12*.personal.finance.GetMonthlySummaryRequest\x1a .personal.finance.MonthlySummaryBKZIgithub.com/eviltomorrow/personal-service/apps/personal-finance/adapter/pbb\x06proto3"

var (
	file_apps_personal_finance_adapter_finance_proto_rawDescOnce sync.Once
	file_apps_personal_finance_adapter_finance_proto_rawDescData []byte
)

func file_apps_personal_finance_adapter_finance_proto_rawDescGZIP() []byte {
	file_apps_personal_finance_adapter_finance_proto_rawDescOnce.Do(func() {
		file_apps_personal_finance_adapter_finance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_personal_finance_adapter_finance_proto_rawDesc), len(file_apps_personal_finance_adapter_finance_proto_rawDesc)))
	})
	return file_apps_personal_finance_adapter_finance_proto_rawDescData
}

var file_apps_personal_finance_adapter_finance_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_apps_personal_finance_adapter_finance_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_apps_personal_finance_adapter_finance_proto_goTypes = []any{
	(FinanceType)(0),                 // 0: personal.finance.FinanceType
	(*Category)(nil),                 // 1: personal.finance.Category
	(*Transaction)(nil),              // 2: personal.finance.Transaction
	(*ListCategoriesResponse)(nil),   // 3: personal.finance.ListCategoriesResponse
	(*CreateCategoryRequest)(nil),    // 4: personal.finance.CreateCategoryRequest
	(*UpdateCategoryRequest)(nil),    // 5: personal.finance.UpdateCategoryRequest
	(*DeleteCategoryRequest)(nil),    // 6: personal.finance.DeleteCategoryRequest
	(*ListTransactionsRequest)(nil),  // 7: personal.finance.ListTransactionsRequest
	(*ListTransactionsResponse)(nil), // 8: personal.finance.ListTransactionsResponse
	(*CreateTransactionRequest)(nil), // 9: personal.finance.CreateTransactionRequest
	(*UpdateTransactionRequest)(nil), // 10: personal.finance.UpdateTransactionRequest
	(*DeleteTransactionRequest)(nil), // 11: personal.finance.DeleteTransactionRequest
	(*GetMonthlySummaryRequest)(nil), // 12: personal.finance.GetMonthlySummaryRequest
	(*CategorySummary)(nil),          // 13: personal.finance.CategorySummary
	(*MonthlySummary)(nil),           // 14: personal.finance.MonthlySummary
	(*emptypb.Empty)(nil),            // 15: google.protobuf.Empty
}
var file_apps_personal_finance_adapter_finance_proto_depIdxs = []int32{
	0,  // 0: personal.finance.Category.type:type_name -> personal.finance.FinanceType
	0,  // 1: personal.finance.Transaction.type:type_name -> personal.finance.FinanceType
	1,  // 2: personal.finance.ListCategoriesResponse.categories:type_name -> personal.finance.Category
	0,  // 3: personal.finance.CreateCategoryRequest.type:type_name -> personal.finance.FinanceType
	0,  // 4: personal.finance.UpdateCategoryRequest.type:type_name -> personal.finance.FinanceType
	2,  // 5: personal.finance.ListTransactionsResponse.transactions:type_name -> personal.finance.Transaction
	0,  // 6: personal.finance.CreateTransactionRequest.type:type_name -> personal.finance.FinanceType
	0,  // 7: personal.finance.UpdateTransactionRequest.type:type_name -> personal.finance.FinanceType
	13, // 8: personal.finance.MonthlySummary.category_summaries:type_name -> personal.finance.CategorySummary
	15, // 9: personal.finance.Finance.ListCategories:input_type -> google.protobuf.Empty
	4,  // 10: personal.finance.Finance.CreateCategory:input_type -> personal.finance.CreateCategoryRequest
	5,  // 11: personal.finance.Finance.UpdateCategory:input_type -> personal.finance.UpdateCategoryRequest
	6,  // 12: personal.finance.Finance.DeleteCategory:input_type -> personal.finance.DeleteCategoryRequest
	7,  // 13: personal.finance.Finance.ListTransactions:input_type -> personal.finance.ListTransactionsRequest
	9,  // 14: personal.finance.Finance.CreateTransaction:input_type -> personal.finance.CreateTransactionRequest
	10, // 15: personal.finance.Finance.UpdateTransaction:input_type -> personal.finance.UpdateTransactionRequest
	11, // 16: personal.finance.Finance.DeleteTransaction:input_type -> personal.finance.DeleteTransactionRequest
	12, // 17: personal.finance.Finance.GetMonthlySummary:input_type -> personal.finance.GetMonthlySummaryRequest
	3,  // 18: personal.finance.Finance.ListCategories:output_type -> personal.finance.ListCategoriesResponse
	1,  // 19: personal.finance.Finance.CreateCategory:output_type -> personal.finance.Category
	1,  // 20: personal.finance.Finance.UpdateCategory:output_type -> personal.finance.Category
	15, // 21: personal.finance.Finance.DeleteCategory:output_type -> google.protobuf.Empty
	8,  // 22: personal.finance.Finance.ListTransactions:output_type -> personal.finance.ListTransactionsResponse
	2,  // 23: personal.finance.Finance.CreateTransaction:output_type -> personal.finance.Transaction
	2,  // 24: personal.finance.Finance.UpdateTransaction:output_type -> personal.finance.Transaction
	15, // 25: personal.finance.Finance.DeleteTransaction:output_type -> google.protobuf.Empty
	14, // 26: personal.finance.Finance.GetMonthlySummary:output_type -> personal.finance.MonthlySummary
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_apps_personal_finance_adapter_finance_proto_init() }
func file_apps_personal_finance_adapter_finance_proto_init() {
	if File_apps_personal_finance_adapter_finance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_personal_finance_adapter_finance_proto_rawDesc), len(file_apps_personal_finance_adapter_finance_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_personal_finance_adapter_finance_proto_goTypes,
		DependencyIndexes: file_apps_personal_finance_adapter_finance_proto_depIdxs,
		EnumInfos:         file_apps_personal_finance_adapter_finance_proto_enumTypes,
		MessageInfos:      file_apps_personal_finance_adapter_finance_proto_msgTypes,
	}.Build()
	File_apps_personal_finance_adapter_finance_proto = out.File
	file_apps_personal_finance_adapter_finance_proto_goTypes = nil
	file_apps_personal_finance_adapter_finance_proto_depIdxs = nil
}
