// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: apps/personal-core/adapter/balance_sheet.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BalanceSheet_ListItems_FullMethodName            = "/personal.core.BalanceSheet/ListItems"
	BalanceSheet_CreateItem_FullMethodName           = "/personal.core.BalanceSheet/CreateItem"
	BalanceSheet_UpdateItem_FullMethodName           = "/personal.core.BalanceSheet/UpdateItem"
	BalanceSheet_DeleteItem_FullMethodName           = "/personal.core.BalanceSheet/DeleteItem"
	BalanceSheet_ListMonthlySummaries_FullMethodName = "/personal.core.BalanceSheet/ListMonthlySummaries"
)

// BalanceSheetClient is the client API for BalanceSheet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BalanceSheetClient interface {
	ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error)
	CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*BalanceSheetItem, error)
	UpdateItem(ctx context.Context, in *UpdateItemRequest, opts ...grpc.CallOption) (*BalanceSheetItem, error)
	DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListMonthlySummaries(ctx context.Context, in *ListMonthlySummariesRequest, opts ...grpc.CallOption) (*ListMonthlySummariesResponse, error)
}

type balanceSheetClient struct {
	cc grpc.ClientConnInterface
}

func NewBalanceSheetClient(cc grpc.ClientConnInterface) BalanceSheetClient {
	return &balanceSheetClient{cc}
}

func (c *balanceSheetClient) ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListItemsResponse)
	err := c.cc.Invoke(ctx, BalanceSheet_ListItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceSheetClient) CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*BalanceSheetItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalanceSheetItem)
	err := c.cc.Invoke(ctx, BalanceSheet_CreateItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceSheetClient) UpdateItem(ctx context.Context, in *UpdateItemRequest, opts ...grpc.CallOption) (*BalanceSheetItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalanceSheetItem)
	err := c.cc.Invoke(ctx, BalanceSheet_UpdateItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceSheetClient) DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BalanceSheet_DeleteItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *balanceSheetClient) ListMonthlySummaries(ctx context.Context, in *ListMonthlySummariesRequest, opts ...grpc.CallOption) (*ListMonthlySummariesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMonthlySummariesResponse)
	err := c.cc.Invoke(ctx, BalanceSheet_ListMonthlySummaries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BalanceSheetServer is the server API for BalanceSheet service.
// All implementations must embed UnimplementedBalanceSheetServer
// for forward compatibility.
type BalanceSheetServer interface {
	ListItems(context.Context, *ListItemsRequest) (*ListItemsResponse, error)
	CreateItem(context.Context, *CreateItemRequest) (*BalanceSheetItem, error)
	UpdateItem(context.Context, *UpdateItemRequest) (*BalanceSheetItem, error)
	DeleteItem(context.Context, *DeleteItemRequest) (*emptypb.Empty, error)
	ListMonthlySummaries(context.Context, *ListMonthlySummariesRequest) (*ListMonthlySummariesResponse, error)
	mustEmbedUnimplementedBalanceSheetServer()
}

// UnimplementedBalanceSheetServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBalanceSheetServer struct{}

func (UnimplementedBalanceSheetServer) ListItems(context.Context, *ListItemsRequest) (*ListItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListItems not implemented")
}
func (UnimplementedBalanceSheetServer) CreateItem(context.Context, *CreateItemRequest) (*BalanceSheetItem, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateItem not implemented")
}
func (UnimplementedBalanceSheetServer) UpdateItem(context.Context, *UpdateItemRequest) (*BalanceSheetItem, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateItem not implemented")
}
func (UnimplementedBalanceSheetServer) DeleteItem(context.Context, *DeleteItemRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteItem not implemented")
}
func (UnimplementedBalanceSheetServer) ListMonthlySummaries(context.Context, *ListMonthlySummariesRequest) (*ListMonthlySummariesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMonthlySummaries not implemented")
}
func (UnimplementedBalanceSheetServer) mustEmbedUnimplementedBalanceSheetServer() {}
func (UnimplementedBalanceSheetServer) testEmbeddedByValue()                      {}

// UnsafeBalanceSheetServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BalanceSheetServer will
// result in compilation errors.
type UnsafeBalanceSheetServer interface {
	mustEmbedUnimplementedBalanceSheetServer()
}

func RegisterBalanceSheetServer(s grpc.ServiceRegistrar, srv BalanceSheetServer) {
	// If the following call panics, it indicates UnimplementedBalanceSheetServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BalanceSheet_ServiceDesc, srv)
}

func _BalanceSheet_ListItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceSheetServer).ListItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceSheet_ListItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceSheetServer).ListItems(ctx, req.(*ListItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceSheet_CreateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceSheetServer).CreateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceSheet_CreateItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceSheetServer).CreateItem(ctx, req.(*CreateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceSheet_UpdateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceSheetServer).UpdateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceSheet_UpdateItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceSheetServer).UpdateItem(ctx, req.(*UpdateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceSheet_DeleteItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceSheetServer).DeleteItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceSheet_DeleteItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceSheetServer).DeleteItem(ctx, req.(*DeleteItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BalanceSheet_ListMonthlySummaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMonthlySummariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BalanceSheetServer).ListMonthlySummaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BalanceSheet_ListMonthlySummaries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BalanceSheetServer).ListMonthlySummaries(ctx, req.(*ListMonthlySummariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BalanceSheet_ServiceDesc is the grpc.ServiceDesc for BalanceSheet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BalanceSheet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "personal.core.BalanceSheet",
	HandlerType: (*BalanceSheetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListItems",
			Handler:    _BalanceSheet_ListItems_Handler,
		},
		{
			MethodName: "CreateItem",
			Handler:    _BalanceSheet_CreateItem_Handler,
		},
		{
			MethodName: "UpdateItem",
			Handler:    _BalanceSheet_UpdateItem_Handler,
		},
		{
			MethodName: "DeleteItem",
			Handler:    _BalanceSheet_DeleteItem_Handler,
		},
		{
			MethodName: "ListMonthlySummaries",
			Handler:    _BalanceSheet_ListMonthlySummaries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/personal-core/adapter/balance_sheet.proto",
}
