// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: apps/personal-core/adapter/balance_sheet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BalanceSheetSection int32

const (
	BalanceSheetSection_BALANCE_SHEET_SECTION_UNSPECIFIED BalanceSheetSection = 0
	BalanceSheetSection_BALANCE_SHEET_SECTION_ASSET       BalanceSheetSection = 1
	BalanceSheetSection_BALANCE_SHEET_SECTION_LIABILITY   BalanceSheetSection = 2
	BalanceSheetSection_BALANCE_SHEET_SECTION_EQUITY      BalanceSheetSection = 3
)

// Enum value maps for BalanceSheetSection.
var (
	BalanceSheetSection_name = map[int32]string{
		0: "BALANCE_SHEET_SECTION_UNSPECIFIED",
		1: "BALANCE_SHEET_SECTION_ASSET",
		2: "BALANCE_SHEET_SECTION_LIABILITY",
		3: "BALANCE_SHEET_SECTION_EQUITY",
	}
	BalanceSheetSection_value = map[string]int32{
		"BALANCE_SHEET_SECTION_UNSPECIFIED": 0,
		"BALANCE_SHEET_SECTION_ASSET":       1,
		"BALANCE_SHEET_SECTION_LIABILITY":   2,
		"BALANCE_SHEET_SECTION_EQUITY":      3,
	}
)

func (x BalanceSheetSection) Enum() *BalanceSheetSection {
	p := new(BalanceSheetSection)
	*p = x
	return p
}

func (x BalanceSheetSection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BalanceSheetSection) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_personal_core_adapter_balance_sheet_proto_enumTypes[0].Descriptor()
}

func (BalanceSheetSection) Type() protoreflect.EnumType {
	return &file_apps_personal_core_adapter_balance_sheet_proto_enumTypes[0]
}

func (x BalanceSheetSection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BalanceSheetSection.Descriptor instead.
func (BalanceSheetSection) EnumDescriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_balance_sheet_proto_rawDescGZIP(), []int{0}
}

type BalanceSheetItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Section       BalanceSheetSection    `protobuf:"varint,3,opt,name=section,proto3,enum=personal.core.BalanceSheetSection" json:"section,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Amount        int64                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Note          string                 `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	Date          string                 `protobuf:"bytes,8,opt,name=date,proto3" json:"date,omitempty"`
	SortOrder     int32                  `protobuf:"varint,9,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceSheetItem) Reset() {
	*x = BalanceSheetItem{}
	mi := &file_apps_personal_core_adapter_balance_sheet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceSheetItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceSheetItem) ProtoMessage() {}

func (x *BalanceSheetItem) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_core_adapter_balance_sheet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceSheetItem.ProtoReflect.Descriptor instead.
func (*BalanceSheetItem) Descriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_balance_sheet_proto_rawDescGZIP(), []int{0}
}

func (x *BalanceSheetItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BalanceSheetItem) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *BalanceSheetItem) GetSection() BalanceSheetSection {
	if x != nil {
		return x.Section
	}
	return BalanceSheetSection_BALANCE_SHEET_SECTION_UNSPECIFIED
}

func (x *BalanceSheetItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *BalanceSheetItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BalanceSheetItem) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BalanceSheetItem) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *BalanceSheetItem) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *BalanceSheetItem) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *BalanceSheetItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *BalanceSheetItem) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ListItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_apps_personal_core_adapter_balance_sheet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_core_adapter_balance_sheet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_balance_sheet_proto_rawDescGZIP(), []int{1}
}

func (x *ListItemsRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ListItemsRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type ListItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BalanceSheetItem    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsResponse) Reset() {
	*x = ListItemsResponse{}
	mi := &file_apps_personal_core_adapter_balance_sheet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsResponse) ProtoMessage() {}

func (x *ListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_core_adapter_balance_sheet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsResponse.ProtoReflect.Descriptor instead.
func (*ListItemsResponse) Descriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_balance_sheet_proto_rawDescGZIP(), []int{2}
}

func (x *ListItemsResponse) GetItems() []*BalanceSheetItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Note          string                 `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	Date          string                 `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	SortOrder     int32                  `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_apps_personal_core_adapter_balance_sheet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_core_adapter_balance_sheet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_balance_sheet_proto_rawDescGZIP(), []int{3}
}

func (x *CreateItemRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateItemRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateItemRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *CreateItemRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CreateItemRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type UpdateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Note          string                 `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	Date          string                 `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`
	SortOrder     int32                  `protobuf:"varint,7,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemRequest) Reset() {
	*x = UpdateItemRequest{}
	mi := &file_apps_personal_core_adapter_balance_sheet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemRequest) ProtoMessage() {}

func (x *UpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_core_adapter_balance_sheet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_balance_sheet_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateItemRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateItemRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateItemRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateItemRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *UpdateItemRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *UpdateItemRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type DeleteItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemRequest) Reset() {
	*x = DeleteItemRequest{}
	mi := &file_apps_personal_core_adapter_balance_sheet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemRequest) ProtoMessage() {}

func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_core_adapter_balance_sheet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_balance_sheet_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteItemRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_apps_personal_core_adapter_balance_sheet_proto protoreflect.FileDescriptor

const file_apps_personal_core_adapter_balance_sheet_proto_rawDesc = "" +
	"\n" +
	".apps/personal-core/adapter/balance_sheet.proto\x12\rpersonal.core\x1a\x1bgoogle/protobuf/empty.proto\"\xcc\x02\n" +
	"\x10BalanceSheetItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12<\n" +
	"\asection\x18\x03 \x01(\x0e2\".personal.core.BalanceSheetSectionR\asection\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x03R\x06amount\x12\x12\n" +
	"\x04note\x18\a \x01(\tR\x04note\x12\x12\n" +
	"\x04date\x18\b \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"sort_order\x18\t \x01(\x05R\tsortOrder\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\"<\n" +
	"\x10ListItemsRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\"J\n" +
	"\x11ListItemsResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.personal.core.BalanceSheetItemR\x05items\"\xa2\x01\n" +
	"\x11CreateItemRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\x12\x12\n" +
	"\x04date\x18\x05 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x05R\tsortOrder\"\xb2\x01\n" +
	"\x11UpdateItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\x12\x12\n" +
	"\x04date\x18\x06 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"sort_order\x18\a \x01(\x05R\tsortOrder\"#\n" +
	"\x11DeleteItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id*\xa4\x01\n" +
	"\x13BalanceSheetSection\x12%\n" +
	"!BALANCE_SHEET_SECTION_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bBALANCE_SHEET_SECTION_ASSET\x10\x01\x12#\n" +
	"\x1fBALANCE_SHEET_SECTION_LIABILITY\x10\x02\x12 \n" +
	"\x1cBALANCE_SHEET_SECTION_EQUITY\x10\x032\xc8\x02\n" +
	"\fBalanceSheet\x12N\n" +
	"\tListItems\x12\x1f.personal.core.ListItemsRequest\x1a .personal.core.ListItemsResponse\x12O\n" +
	"\n" +
	"CreateItem\x12 .personal.core.CreateItemRequest\x1a\x1f.personal.core.BalanceSheetItem\x12O\n" +
	"\n" +
	"UpdateItem\x12 .personal.core.UpdateItemRequest\x1a\x1f.personal.core.BalanceSheetItem\x12F\n" +
	"\n" +
	"DeleteItem\x12 .personal.core.DeleteItemRequest\x1a\x16.google.protobuf.EmptyBHZFgithub.com/eviltomorrow/personal-service/apps/personal-core/adapter/pbb\x06proto3"

var (
	file_apps_personal_core_adapter_balance_sheet_proto_rawDescOnce sync.Once
	file_apps_personal_core_adapter_balance_sheet_proto_rawDescData []byte
)

func file_apps_personal_core_adapter_balance_sheet_proto_rawDescGZIP() []byte {
	file_apps_personal_core_adapter_balance_sheet_proto_rawDescOnce.Do(func() {
		file_apps_personal_core_adapter_balance_sheet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_personal_core_adapter_balance_sheet_proto_rawDesc), len(file_apps_personal_core_adapter_balance_sheet_proto_rawDesc)))
	})
	return file_apps_personal_core_adapter_balance_sheet_proto_rawDescData
}

var file_apps_personal_core_adapter_balance_sheet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_apps_personal_core_adapter_balance_sheet_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_apps_personal_core_adapter_balance_sheet_proto_goTypes = []any{
	(BalanceSheetSection)(0),  // 0: personal.core.BalanceSheetSection
	(*BalanceSheetItem)(nil),  // 1: personal.core.BalanceSheetItem
	(*ListItemsRequest)(nil),  // 2: personal.core.ListItemsRequest
	(*ListItemsResponse)(nil), // 3: personal.core.ListItemsResponse
	(*CreateItemRequest)(nil), // 4: personal.core.CreateItemRequest
	(*UpdateItemRequest)(nil), // 5: personal.core.UpdateItemRequest
	(*DeleteItemRequest)(nil), // 6: personal.core.DeleteItemRequest
	(*emptypb.Empty)(nil),     // 7: google.protobuf.Empty
}
var file_apps_personal_core_adapter_balance_sheet_proto_depIdxs = []int32{
	0, // 0: personal.core.BalanceSheetItem.section:type_name -> personal.core.BalanceSheetSection
	1, // 1: personal.core.ListItemsResponse.items:type_name -> personal.core.BalanceSheetItem
	2, // 2: personal.core.BalanceSheet.ListItems:input_type -> personal.core.ListItemsRequest
	4, // 3: personal.core.BalanceSheet.CreateItem:input_type -> personal.core.CreateItemRequest
	5, // 4: personal.core.BalanceSheet.UpdateItem:input_type -> personal.core.UpdateItemRequest
	6, // 5: personal.core.BalanceSheet.DeleteItem:input_type -> personal.core.DeleteItemRequest
	3, // 6: personal.core.BalanceSheet.ListItems:output_type -> personal.core.ListItemsResponse
	1, // 7: personal.core.BalanceSheet.CreateItem:output_type -> personal.core.BalanceSheetItem
	1, // 8: personal.core.BalanceSheet.UpdateItem:output_type -> personal.core.BalanceSheetItem
	7, // 9: personal.core.BalanceSheet.DeleteItem:output_type -> google.protobuf.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_apps_personal_core_adapter_balance_sheet_proto_init() }
func file_apps_personal_core_adapter_balance_sheet_proto_init() {
	if File_apps_personal_core_adapter_balance_sheet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_personal_core_adapter_balance_sheet_proto_rawDesc), len(file_apps_personal_core_adapter_balance_sheet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_personal_core_adapter_balance_sheet_proto_goTypes,
		DependencyIndexes: file_apps_personal_core_adapter_balance_sheet_proto_depIdxs,
		EnumInfos:         file_apps_personal_core_adapter_balance_sheet_proto_enumTypes,
		MessageInfos:      file_apps_personal_core_adapter_balance_sheet_proto_msgTypes,
	}.Build()
	File_apps_personal_core_adapter_balance_sheet_proto = out.File
	file_apps_personal_core_adapter_balance_sheet_proto_goTypes = nil
	file_apps_personal_core_adapter_balance_sheet_proto_depIdxs = nil
}
