// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: apps/personal-core/adapter/portfolio.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Portfolio_ListPositions_FullMethodName  = "/personal.core.Portfolio/ListPositions"
	Portfolio_CreatePosition_FullMethodName = "/personal.core.Portfolio/CreatePosition"
	Portfolio_UpdatePosition_FullMethodName = "/personal.core.Portfolio/UpdatePosition"
	Portfolio_DeletePosition_FullMethodName = "/personal.core.Portfolio/DeletePosition"
	Portfolio_ListTrades_FullMethodName     = "/personal.core.Portfolio/ListTrades"
	Portfolio_CreateTrade_FullMethodName    = "/personal.core.Portfolio/CreateTrade"
	Portfolio_UpdateTrade_FullMethodName    = "/personal.core.Portfolio/UpdateTrade"
	Portfolio_DeleteTrade_FullMethodName    = "/personal.core.Portfolio/DeleteTrade"
	Portfolio_ListSnapshots_FullMethodName  = "/personal.core.Portfolio/ListSnapshots"
	Portfolio_UpsertSnapshot_FullMethodName = "/personal.core.Portfolio/UpsertSnapshot"
	Portfolio_GetConfig_FullMethodName      = "/personal.core.Portfolio/GetConfig"
	Portfolio_UpdateConfig_FullMethodName   = "/personal.core.Portfolio/UpdateConfig"
)

// PortfolioClient is the client API for Portfolio service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PortfolioClient interface {
	ListPositions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListPositionsResponse, error)
	CreatePosition(ctx context.Context, in *CreatePositionRequest, opts ...grpc.CallOption) (*Position, error)
	UpdatePosition(ctx context.Context, in *UpdatePositionRequest, opts ...grpc.CallOption) (*Position, error)
	DeletePosition(ctx context.Context, in *DeletePositionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListTrades(ctx context.Context, in *ListTradesRequest, opts ...grpc.CallOption) (*ListTradesResponse, error)
	CreateTrade(ctx context.Context, in *CreateTradeRequest, opts ...grpc.CallOption) (*Trade, error)
	UpdateTrade(ctx context.Context, in *UpdateTradeRequest, opts ...grpc.CallOption) (*Trade, error)
	DeleteTrade(ctx context.Context, in *DeleteTradeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListSnapshots(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListSnapshotsResponse, error)
	UpsertSnapshot(ctx context.Context, in *UpsertSnapshotRequest, opts ...grpc.CallOption) (*ValueSnapshot, error)
	GetConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PortfolioConfig, error)
	UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*PortfolioConfig, error)
}

type portfolioClient struct {
	cc grpc.ClientConnInterface
}

func NewPortfolioClient(cc grpc.ClientConnInterface) PortfolioClient {
	return &portfolioClient{cc}
}

func (c *portfolioClient) ListPositions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListPositionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPositionsResponse)
	err := c.cc.Invoke(ctx, Portfolio_ListPositions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioClient) CreatePosition(ctx context.Context, in *CreatePositionRequest, opts ...grpc.CallOption) (*Position, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Position)
	err := c.cc.Invoke(ctx, Portfolio_CreatePosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioClient) UpdatePosition(ctx context.Context, in *UpdatePositionRequest, opts ...grpc.CallOption) (*Position, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Position)
	err := c.cc.Invoke(ctx, Portfolio_UpdatePosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioClient) DeletePosition(ctx context.Context, in *DeletePositionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Portfolio_DeletePosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioClient) ListTrades(ctx context.Context, in *ListTradesRequest, opts ...grpc.CallOption) (*ListTradesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTradesResponse)
	err := c.cc.Invoke(ctx, Portfolio_ListTrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioClient) CreateTrade(ctx context.Context, in *CreateTradeRequest, opts ...grpc.CallOption) (*Trade, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Trade)
	err := c.cc.Invoke(ctx, Portfolio_CreateTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioClient) UpdateTrade(ctx context.Context, in *UpdateTradeRequest, opts ...grpc.CallOption) (*Trade, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Trade)
	err := c.cc.Invoke(ctx, Portfolio_UpdateTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioClient) DeleteTrade(ctx context.Context, in *DeleteTradeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Portfolio_DeleteTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioClient) ListSnapshots(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnapshotsResponse)
	err := c.cc.Invoke(ctx, Portfolio_ListSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioClient) UpsertSnapshot(ctx context.Context, in *UpsertSnapshotRequest, opts ...grpc.CallOption) (*ValueSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValueSnapshot)
	err := c.cc.Invoke(ctx, Portfolio_UpsertSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioClient) GetConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PortfolioConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PortfolioConfig)
	err := c.cc.Invoke(ctx, Portfolio_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioClient) UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*PortfolioConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PortfolioConfig)
	err := c.cc.Invoke(ctx, Portfolio_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortfolioServer is the server API for Portfolio service.
// All implementations must embed UnimplementedPortfolioServer
// for forward compatibility.
type PortfolioServer interface {
	ListPositions(context.Context, *emptypb.Empty) (*ListPositionsResponse, error)
	CreatePosition(context.Context, *CreatePositionRequest) (*Position, error)
	UpdatePosition(context.Context, *UpdatePositionRequest) (*Position, error)
	DeletePosition(context.Context, *DeletePositionRequest) (*emptypb.Empty, error)
	ListTrades(context.Context, *ListTradesRequest) (*ListTradesResponse, error)
	CreateTrade(context.Context, *CreateTradeRequest) (*Trade, error)
	UpdateTrade(context.Context, *UpdateTradeRequest) (*Trade, error)
	DeleteTrade(context.Context, *DeleteTradeRequest) (*emptypb.Empty, error)
	ListSnapshots(context.Context, *emptypb.Empty) (*ListSnapshotsResponse, error)
	UpsertSnapshot(context.Context, *UpsertSnapshotRequest) (*ValueSnapshot, error)
	GetConfig(context.Context, *emptypb.Empty) (*PortfolioConfig, error)
	UpdateConfig(context.Context, *UpdateConfigRequest) (*PortfolioConfig, error)
	mustEmbedUnimplementedPortfolioServer()
}

// UnimplementedPortfolioServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPortfolioServer struct{}

func (UnimplementedPortfolioServer) ListPositions(context.Context, *emptypb.Empty) (*ListPositionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPositions not implemented")
}
func (UnimplementedPortfolioServer) CreatePosition(context.Context, *CreatePositionRequest) (*Position, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePosition not implemented")
}
func (UnimplementedPortfolioServer) UpdatePosition(context.Context, *UpdatePositionRequest) (*Position, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePosition not implemented")
}
func (UnimplementedPortfolioServer) DeletePosition(context.Context, *DeletePositionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePosition not implemented")
}
func (UnimplementedPortfolioServer) ListTrades(context.Context, *ListTradesRequest) (*ListTradesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTrades not implemented")
}
func (UnimplementedPortfolioServer) CreateTrade(context.Context, *CreateTradeRequest) (*Trade, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTrade not implemented")
}
func (UnimplementedPortfolioServer) UpdateTrade(context.Context, *UpdateTradeRequest) (*Trade, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTrade not implemented")
}
func (UnimplementedPortfolioServer) DeleteTrade(context.Context, *DeleteTradeRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTrade not implemented")
}
func (UnimplementedPortfolioServer) ListSnapshots(context.Context, *emptypb.Empty) (*ListSnapshotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (UnimplementedPortfolioServer) UpsertSnapshot(context.Context, *UpsertSnapshotRequest) (*ValueSnapshot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertSnapshot not implemented")
}
func (UnimplementedPortfolioServer) GetConfig(context.Context, *emptypb.Empty) (*PortfolioConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedPortfolioServer) UpdateConfig(context.Context, *UpdateConfigRequest) (*PortfolioConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedPortfolioServer) mustEmbedUnimplementedPortfolioServer() {}
func (UnimplementedPortfolioServer) testEmbeddedByValue()                   {}

// UnsafePortfolioServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortfolioServer will
// result in compilation errors.
type UnsafePortfolioServer interface {
	mustEmbedUnimplementedPortfolioServer()
}

func RegisterPortfolioServer(s grpc.ServiceRegistrar, srv PortfolioServer) {
	// If the following call pancis, it indicates UnimplementedPortfolioServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Portfolio_ServiceDesc, srv)
}

func _Portfolio_ListPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServer).ListPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Portfolio_ListPositions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServer).ListPositions(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Portfolio_CreatePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServer).CreatePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Portfolio_CreatePosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServer).CreatePosition(ctx, req.(*CreatePositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Portfolio_UpdatePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServer).UpdatePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Portfolio_UpdatePosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServer).UpdatePosition(ctx, req.(*UpdatePositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Portfolio_DeletePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServer).DeletePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Portfolio_DeletePosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServer).DeletePosition(ctx, req.(*DeletePositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Portfolio_ListTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServer).ListTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Portfolio_ListTrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServer).ListTrades(ctx, req.(*ListTradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Portfolio_CreateTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServer).CreateTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Portfolio_CreateTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServer).CreateTrade(ctx, req.(*CreateTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Portfolio_UpdateTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServer).UpdateTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Portfolio_UpdateTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServer).UpdateTrade(ctx, req.(*UpdateTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Portfolio_DeleteTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServer).DeleteTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Portfolio_DeleteTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServer).DeleteTrade(ctx, req.(*DeleteTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Portfolio_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Portfolio_ListSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServer).ListSnapshots(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Portfolio_UpsertSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServer).UpsertSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Portfolio_UpsertSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServer).UpsertSnapshot(ctx, req.(*UpsertSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Portfolio_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Portfolio_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServer).GetConfig(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Portfolio_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Portfolio_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServer).UpdateConfig(ctx, req.(*UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Portfolio_ServiceDesc is the grpc.ServiceDesc for Portfolio service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Portfolio_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "personal.core.Portfolio",
	HandlerType: (*PortfolioServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPositions",
			Handler:    _Portfolio_ListPositions_Handler,
		},
		{
			MethodName: "CreatePosition",
			Handler:    _Portfolio_CreatePosition_Handler,
		},
		{
			MethodName: "UpdatePosition",
			Handler:    _Portfolio_UpdatePosition_Handler,
		},
		{
			MethodName: "DeletePosition",
			Handler:    _Portfolio_DeletePosition_Handler,
		},
		{
			MethodName: "ListTrades",
			Handler:    _Portfolio_ListTrades_Handler,
		},
		{
			MethodName: "CreateTrade",
			Handler:    _Portfolio_CreateTrade_Handler,
		},
		{
			MethodName: "UpdateTrade",
			Handler:    _Portfolio_UpdateTrade_Handler,
		},
		{
			MethodName: "DeleteTrade",
			Handler:    _Portfolio_DeleteTrade_Handler,
		},
		{
			MethodName: "ListSnapshots",
			Handler:    _Portfolio_ListSnapshots_Handler,
		},
		{
			MethodName: "UpsertSnapshot",
			Handler:    _Portfolio_UpsertSnapshot_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _Portfolio_GetConfig_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _Portfolio_UpdateConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/personal-core/adapter/portfolio.proto",
}
