// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: apps/personal-core/adapter/portfolio.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PositionType int32

const (
	PositionType_POSITION_TYPE_UNSPECIFIED PositionType = 0
	PositionType_POSITION_TYPE_STOCK       PositionType = 1
	PositionType_POSITION_TYPE_FUTURES     PositionType = 2
)

// Enum value maps for PositionType.
var (
	PositionType_name = map[int32]string{
		0: "POSITION_TYPE_UNSPECIFIED",
		1: "POSITION_TYPE_STOCK",
		2: "POSITION_TYPE_FUTURES",
	}
	PositionType_value = map[string]int32{
		"POSITION_TYPE_UNSPECIFIED": 0,
		"POSITION_TYPE_STOCK":       1,
		"POSITION_TYPE_FUTURES":     2,
	}
)

func (x PositionType) Enum() *PositionType {
	p := new(PositionType)
	*p = x
	return p
}

func (x PositionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PositionType) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_personal_core_adapter_portfolio_proto_enumTypes[0].Descriptor()
}

func (PositionType) Type() protoreflect.EnumType {
	return &file_apps_personal_core_adapter_portfolio_proto_enumTypes[0]
}

func (x PositionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PositionType.Descriptor instead.
func (PositionType) EnumDescriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_portfolio_proto_rawDescGZIP(), []int{0}
}

type TradeType int32

const (
	TradeType_TRADE_TYPE_UNSPECIFIED TradeType = 0
	TradeType_TRADE_TYPE_OPEN        TradeType = 1
	TradeType_TRADE_TYPE_BUY         TradeType = 2
	TradeType_TRADE_TYPE_SELL        TradeType = 3
	TradeType_TRADE_TYPE_CLOSE       TradeType = 4
)

// Enum value maps for TradeType.
var (
	TradeType_name = map[int32]string{
		0: "TRADE_TYPE_UNSPECIFIED",
		1: "TRADE_TYPE_OPEN",
		2: "TRADE_TYPE_BUY",
		3: "TRADE_TYPE_SELL",
		4: "TRADE_TYPE_CLOSE",
	}
	TradeType_value = map[string]int32{
		"TRADE_TYPE_UNSPECIFIED": 0,
		"TRADE_TYPE_OPEN":        1,
		"TRADE_TYPE_BUY":         2,
		"TRADE_TYPE_SELL":        3,
		"TRADE_TYPE_CLOSE":       4,
	}
)

func (x TradeType) Enum() *TradeType {
	p := new(TradeType)
	*p = x
	return p
}

func (x TradeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TradeType) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_personal_core_adapter_portfolio_proto_enumTypes[1].Descriptor()
}

func (TradeType) Type() protoreflect.EnumType {
	return &file_apps_personal_core_adapter_portfolio_proto_enumTypes[1]
}

func (x TradeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TradeType.Descriptor instead.
func (TradeType) EnumDescriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_portfolio_proto_rawDescGZIP(), []int{1}
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Type          PositionType           `protobuf:"varint,5,opt,name=type,proto3,enum=personal.core.PositionType" json:"type,omitempty"`
	Direction     string                 `protobuf:"bytes,6,opt,name=direction,proto3" json:"direction,omitempty"`
	InitialQty    int32                  `protobuf:"varint,7,opt,name=initial_qty,json=initialQty,proto3" json:"initial_qty,omitempty"`
	CurrentPrice  int64                  `protobuf:"varint,8,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	MarginRatio   int32                  `protobuf:"varint,9,opt,name=margin_ratio,json=marginRatio,proto3" json:"margin_ratio,omitempty"`
	SortOrder     int32                  `protobuf:"varint,10,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Archived      bool                   `protobuf:"varint,11,opt,name=archived,proto3" json:"archived,omitempty"`
	ClosedPnl     int64                  `protobuf:"varint,12,opt,name=closed_pnl,json=closedPnl,proto3" json:"closed_pnl,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_portfolio_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Position) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Position) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Position) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Position) GetType() PositionType {
	if x != nil {
		return x.Type
	}
	return PositionType_POSITION_TYPE_UNSPECIFIED
}

func (x *Position) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *Position) GetInitialQty() int32 {
	if x != nil {
		return x.InitialQty
	}
	return 0
}

func (x *Position) GetCurrentPrice() int64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *Position) GetMarginRatio() int32 {
	if x != nil {
		return x.MarginRatio
	}
	return 0
}

func (x *Position) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Position) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *Position) GetClosedPnl() int64 {
	if x != nil {
		return x.ClosedPnl
	}
	return 0
}

func (x *Position) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Position) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	PositionId    int64                  `protobuf:"varint,3,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	Type          TradeType              `protobuf:"varint,4,opt,name=type,proto3,enum=personal.core.TradeType" json:"type,omitempty"`
	Date          string                 `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Price         int64                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Note          string                 `protobuf:"bytes,8,opt,name=note,proto3" json:"note,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Fee           int64                  `protobuf:"varint,11,opt,name=fee,proto3" json:"fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_portfolio_proto_rawDescGZIP(), []int{1}
}

func (x *Trade) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Trade) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Trade) GetPositionId() int64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

func (x *Trade) GetType() TradeType {
	if x != nil {
		return x.Type
	}
	return TradeType_TRADE_TYPE_UNSPECIFIED
}

func (x *Trade) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Trade) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Trade) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Trade) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Trade) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Trade) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Trade) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

type ValueSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	TotalValue    int64                  `protobuf:"varint,2,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueSnapshot) Reset() {
	*x = ValueSnapshot{}
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueSnapshot) ProtoMessage() {}

func (x *ValueSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueSnapshot.ProtoReflect.Descriptor instead.
func (*ValueSnapshot) Descriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_portfolio_proto_rawDescGZIP(), []int{2}
}

func (x *ValueSnapshot) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ValueSnapshot) GetTotalValue() int64 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

type PortfolioConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCapital  int64                  `protobuf:"varint,1,opt,name=total_capital,json=totalCapital,proto3" json:"total_capital,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortfolioConfig) Reset() {
	*x = PortfolioConfig{}
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioConfig) ProtoMessage() {}

func (x *PortfolioConfig) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioConfig.ProtoReflect.Descriptor instead.
func (*PortfolioConfig) Descriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_portfolio_proto_rawDescGZIP(), []int{3}
}

func (x *PortfolioConfig) GetTotalCapital() int64 {
	if x != nil {
		return x.TotalCapital
	}
	return 0
}

type ListPositionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*Position            `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPositionsResponse) Reset() {
	*x = ListPositionsResponse{}
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPositionsResponse) ProtoMessage() {}

func (x *ListPositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPositionsResponse.ProtoReflect.Descriptor instead.
func (*ListPositionsResponse) Descriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_portfolio_proto_rawDescGZIP(), []int{4}
}

func (x *ListPositionsResponse) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

type CreatePositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          PositionType           `protobuf:"varint,3,opt,name=type,proto3,enum=personal.core.PositionType" json:"type,omitempty"`
	Direction     string                 `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	InitialQty    int32                  `protobuf:"varint,5,opt,name=initial_qty,json=initialQty,proto3" json:"initial_qty,omitempty"`
	CurrentPrice  int64                  `protobuf:"varint,6,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	MarginRatio   int32                  `protobuf:"varint,7,opt,name=margin_ratio,json=marginRatio,proto3" json:"margin_ratio,omitempty"`
	SortOrder     int32                  `protobuf:"varint,8,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePositionRequest) Reset() {
	*x = CreatePositionRequest{}
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePositionRequest) ProtoMessage() {}

func (x *CreatePositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePositionRequest.ProtoReflect.Descriptor instead.
func (*CreatePositionRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_portfolio_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePositionRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreatePositionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePositionRequest) GetType() PositionType {
	if x != nil {
		return x.Type
	}
	return PositionType_POSITION_TYPE_UNSPECIFIED
}

func (x *CreatePositionRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *CreatePositionRequest) GetInitialQty() int32 {
	if x != nil {
		return x.InitialQty
	}
	return 0
}

func (x *CreatePositionRequest) GetCurrentPrice() int64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *CreatePositionRequest) GetMarginRatio() int32 {
	if x != nil {
		return x.MarginRatio
	}
	return 0
}

func (x *CreatePositionRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type UpdatePositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          PositionType           `protobuf:"varint,4,opt,name=type,proto3,enum=personal.core.PositionType" json:"type,omitempty"`
	Direction     string                 `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"`
	InitialQty    int32                  `protobuf:"varint,6,opt,name=initial_qty,json=initialQty,proto3" json:"initial_qty,omitempty"`
	CurrentPrice  int64                  `protobuf:"varint,7,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	MarginRatio   int32                  `protobuf:"varint,8,opt,name=margin_ratio,json=marginRatio,proto3" json:"margin_ratio,omitempty"`
	SortOrder     int32                  `protobuf:"varint,9,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Archived      bool                   `protobuf:"varint,10,opt,name=archived,proto3" json:"archived,omitempty"`
	ClosedPnl     int64                  `protobuf:"varint,11,opt,name=closed_pnl,json=closedPnl,proto3" json:"closed_pnl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePositionRequest) Reset() {
	*x = UpdatePositionRequest{}
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePositionRequest) ProtoMessage() {}

func (x *UpdatePositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePositionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePositionRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_portfolio_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePositionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePositionRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdatePositionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePositionRequest) GetType() PositionType {
	if x != nil {
		return x.Type
	}
	return PositionType_POSITION_TYPE_UNSPECIFIED
}

func (x *UpdatePositionRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *UpdatePositionRequest) GetInitialQty() int32 {
	if x != nil {
		return x.InitialQty
	}
	return 0
}

func (x *UpdatePositionRequest) GetCurrentPrice() int64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *UpdatePositionRequest) GetMarginRatio() int32 {
	if x != nil {
		return x.MarginRatio
	}
	return 0
}

func (x *UpdatePositionRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *UpdatePositionRequest) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *UpdatePositionRequest) GetClosedPnl() int64 {
	if x != nil {
		return x.ClosedPnl
	}
	return 0
}

type DeletePositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePositionRequest) Reset() {
	*x = DeletePositionRequest{}
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePositionRequest) ProtoMessage() {}

func (x *DeletePositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePositionRequest.ProtoReflect.Descriptor instead.
func (*DeletePositionRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_portfolio_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePositionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListTradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PositionId    int64                  `protobuf:"varint,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTradesRequest) Reset() {
	*x = ListTradesRequest{}
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTradesRequest) ProtoMessage() {}

func (x *ListTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTradesRequest.ProtoReflect.Descriptor instead.
func (*ListTradesRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_portfolio_proto_rawDescGZIP(), []int{8}
}

func (x *ListTradesRequest) GetPositionId() int64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

type ListTradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trades        []*Trade               `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTradesResponse) Reset() {
	*x = ListTradesResponse{}
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTradesResponse) ProtoMessage() {}

func (x *ListTradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTradesResponse.ProtoReflect.Descriptor instead.
func (*ListTradesResponse) Descriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_portfolio_proto_rawDescGZIP(), []int{9}
}

func (x *ListTradesResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

type CreateTradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PositionId    int64                  `protobuf:"varint,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	Type          TradeType              `protobuf:"varint,2,opt,name=type,proto3,enum=personal.core.TradeType" json:"type,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Note          string                 `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	Fee           int64                  `protobuf:"varint,7,opt,name=fee,proto3" json:"fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTradeRequest) Reset() {
	*x = CreateTradeRequest{}
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTradeRequest) ProtoMessage() {}

func (x *CreateTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTradeRequest.ProtoReflect.Descriptor instead.
func (*CreateTradeRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_portfolio_proto_rawDescGZIP(), []int{10}
}

func (x *CreateTradeRequest) GetPositionId() int64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

func (x *CreateTradeRequest) GetType() TradeType {
	if x != nil {
		return x.Type
	}
	return TradeType_TRADE_TYPE_UNSPECIFIED
}

func (x *CreateTradeRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CreateTradeRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateTradeRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateTradeRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *CreateTradeRequest) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

type UpdateTradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          TradeType              `protobuf:"varint,2,opt,name=type,proto3,enum=personal.core.TradeType" json:"type,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Note          string                 `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	Fee           int64                  `protobuf:"varint,7,opt,name=fee,proto3" json:"fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTradeRequest) Reset() {
	*x = UpdateTradeRequest{}
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTradeRequest) ProtoMessage() {}

func (x *UpdateTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTradeRequest.ProtoReflect.Descriptor instead.
func (*UpdateTradeRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_portfolio_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateTradeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTradeRequest) GetType() TradeType {
	if x != nil {
		return x.Type
	}
	return TradeType_TRADE_TYPE_UNSPECIFIED
}

func (x *UpdateTradeRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *UpdateTradeRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateTradeRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UpdateTradeRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *UpdateTradeRequest) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

type DeleteTradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTradeRequest) Reset() {
	*x = DeleteTradeRequest{}
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTradeRequest) ProtoMessage() {}

func (x *DeleteTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTradeRequest.ProtoReflect.Descriptor instead.
func (*DeleteTradeRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_portfolio_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteTradeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListSnapshotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*ValueSnapshot       `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsResponse) Reset() {
	*x = ListSnapshotsResponse{}
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsResponse) ProtoMessage() {}

func (x *ListSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*ListSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_portfolio_proto_rawDescGZIP(), []int{13}
}

func (x *ListSnapshotsResponse) GetSnapshots() []*ValueSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type UpsertSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	TotalValue    int64                  `protobuf:"varint,2,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertSnapshotRequest) Reset() {
	*x = UpsertSnapshotRequest{}
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertSnapshotRequest) ProtoMessage() {}

func (x *UpsertSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertSnapshotRequest.ProtoReflect.Descriptor instead.
func (*UpsertSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_portfolio_proto_rawDescGZIP(), []int{14}
}

func (x *UpsertSnapshotRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *UpsertSnapshotRequest) GetTotalValue() int64 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

type UpdateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCapital  int64                  `protobuf:"varint,1,opt,name=total_capital,json=totalCapital,proto3" json:"total_capital,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_core_adapter_portfolio_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_portfolio_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateConfigRequest) GetTotalCapital() int64 {
	if x != nil {
		return x.TotalCapital
	}
	return 0
}

var File_apps_personal_core_adapter_portfolio_proto protoreflect.FileDescriptor

const file_apps_personal_core_adapter_portfolio_proto_rawDesc = "" +
	"\n" +
	"*apps/personal-core/adapter/portfolio.proto\x12\rpersonal.core\x1a\x1bgoogle/protobuf/empty.proto\"\xb1\x03\n" +
	"\bPosition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12/\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1b.personal.core.PositionTypeR\x04type\x12\x1c\n" +
	"\tdirection\x18\x06 \x01(\tR\tdirection\x12\x1f\n" +
	"\vinitial_qty\x18\a \x01(\x05R\n" +
	"initialQty\x12#\n" +
	"\rcurrent_price\x18\b \x01(\x03R\fcurrentPrice\x12!\n" +
	"\fmargin_ratio\x18\t \x01(\x05R\vmarginRatio\x12\x1d\n" +
	"\n" +
	"sort_order\x18\n" +
	" \x01(\x05R\tsortOrder\x12\x1a\n" +
	"\barchived\x18\v \x01(\bR\barchived\x12\x1d\n" +
	"\n" +
	"closed_pnl\x18\f \x01(\x03R\tclosedPnl\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\x03R\tupdatedAt\"\xaf\x02\n" +
	"\x05Trade\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x1f\n" +
	"\vposition_id\x18\x03 \x01(\x03R\n" +
	"positionId\x12,\n" +
	"\x04type\x18\x04 \x01(\x0e2\x18.personal.core.TradeTypeR\x04type\x12\x12\n" +
	"\x04date\x18\x05 \x01(\tR\x04date\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x05R\bquantity\x12\x12\n" +
	"\x04note\x18\b \x01(\tR\x04note\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\x12\x10\n" +
	"\x03fee\x18\v \x01(\x03R\x03fee\"D\n" +
	"\rValueSnapshot\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1f\n" +
	"\vtotal_value\x18\x02 \x01(\x03R\n" +
	"totalValue\"6\n" +
	"\x0fPortfolioConfig\x12#\n" +
	"\rtotal_capital\x18\x01 \x01(\x03R\ftotalCapital\"N\n" +
	"\x15ListPositionsResponse\x125\n" +
	"\tpositions\x18\x01 \x03(\v2\x17.personal.core.PositionR\tpositions\"\x96\x02\n" +
	"\x15CreatePositionRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1b.personal.core.PositionTypeR\x04type\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\x12\x1f\n" +
	"\vinitial_qty\x18\x05 \x01(\x05R\n" +
	"initialQty\x12#\n" +
	"\rcurrent_price\x18\x06 \x01(\x03R\fcurrentPrice\x12!\n" +
	"\fmargin_ratio\x18\a \x01(\x05R\vmarginRatio\x12\x1d\n" +
	"\n" +
	"sort_order\x18\b \x01(\x05R\tsortOrder\"\xe1\x02\n" +
	"\x15UpdatePositionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12/\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1b.personal.core.PositionTypeR\x04type\x12\x1c\n" +
	"\tdirection\x18\x05 \x01(\tR\tdirection\x12\x1f\n" +
	"\vinitial_qty\x18\x06 \x01(\x05R\n" +
	"initialQty\x12#\n" +
	"\rcurrent_price\x18\a \x01(\x03R\fcurrentPrice\x12!\n" +
	"\fmargin_ratio\x18\b \x01(\x05R\vmarginRatio\x12\x1d\n" +
	"\n" +
	"sort_order\x18\t \x01(\x05R\tsortOrder\x12\x1a\n" +
	"\barchived\x18\n" +
	" \x01(\bR\barchived\x12\x1d\n" +
	"\n" +
	"closed_pnl\x18\v \x01(\x03R\tclosedPnl\"'\n" +
	"\x15DeletePositionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"4\n" +
	"\x11ListTradesRequest\x12\x1f\n" +
	"\vposition_id\x18\x01 \x01(\x03R\n" +
	"positionId\"B\n" +
	"\x12ListTradesResponse\x12,\n" +
	"\x06trades\x18\x01 \x03(\v2\x14.personal.core.TradeR\x06trades\"\xcf\x01\n" +
	"\x12CreateTradeRequest\x12\x1f\n" +
	"\vposition_id\x18\x01 \x01(\x03R\n" +
	"positionId\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.personal.core.TradeTypeR\x04type\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\x12\x10\n" +
	"\x03fee\x18\a \x01(\x03R\x03fee\"\xbe\x01\n" +
	"\x12UpdateTradeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.personal.core.TradeTypeR\x04type\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\x12\x10\n" +
	"\x03fee\x18\a \x01(\x03R\x03fee\"$\n" +
	"\x12DeleteTradeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"S\n" +
	"\x15ListSnapshotsResponse\x12:\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x1c.personal.core.ValueSnapshotR\tsnapshots\"L\n" +
	"\x15UpsertSnapshotRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1f\n" +
	"\vtotal_value\x18\x02 \x01(\x03R\n" +
	"totalValue\":\n" +
	"\x13UpdateConfigRequest\x12#\n" +
	"\rtotal_capital\x18\x01 \x01(\x03R\ftotalCapital*a\n" +
	"\fPositionType\x12\x1d\n" +
	"\x19POSITION_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13POSITION_TYPE_STOCK\x10\x01\x12\x19\n" +
	"\x15POSITION_TYPE_FUTURES\x10\x02*{\n" +
	"\tTradeType\x12\x1a\n" +
	"\x16TRADE_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fTRADE_TYPE_OPEN\x10\x01\x12\x12\n" +
	"\x0eTRADE_TYPE_BUY\x10\x02\x12\x13\n" +
	"\x0fTRADE_TYPE_SELL\x10\x03\x12\x14\n" +
	"\x10TRADE_TYPE_CLOSE\x10\x042\xb7\a\n" +
	"\tPortfolio\x12M\n" +
	"\rListPositions\x12\x16.google.protobuf.Empty\x1a$.personal.core.ListPositionsResponse\x12O\n" +
	"\x0eCreatePosition\x12$.personal.core.CreatePositionRequest\x1a\x17.personal.core.Position\x12O\n" +
	"\x0eUpdatePosition\x12$.personal.core.UpdatePositionRequest\x1a\x17.personal.core.Position\x12N\n" +
	"\x0eDeletePosition\x12$.personal.core.DeletePositionRequest\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\n" +
	"ListTrades\x12 .personal.core.ListTradesRequest\x1a!.personal.core.ListTradesResponse\x12F\n" +
	"\vCreateTrade\x12!.personal.core.CreateTradeRequest\x1a\x14.personal.core.Trade\x12F\n" +
	"\vUpdateTrade\x12!.personal.core.UpdateTradeRequest\x1a\x14.personal.core.Trade\x12H\n" +
	"\vDeleteTrade\x12!.personal.core.DeleteTradeRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\rListSnapshots\x12\x16.google.protobuf.Empty\x1a$.personal.core.ListSnapshotsResponse\x12T\n" +
	"\x0eUpsertSnapshot\x12$.personal.core.UpsertSnapshotRequest\x1a\x1c.personal.core.ValueSnapshot\x12C\n" +
	"\tGetConfig\x12\x16.google.protobuf.Empty\x1a\x1e.personal.core.PortfolioConfig\x12R\n" +
	"\fUpdateConfig\x12\".personal.core.UpdateConfigRequest\x1a\x1e.personal.core.PortfolioConfigBHZFgithub.com/eviltomorrow/personal-service/apps/personal-core/adapter/pbb\x06proto3"

var (
	file_apps_personal_core_adapter_portfolio_proto_rawDescOnce sync.Once
	file_apps_personal_core_adapter_portfolio_proto_rawDescData []byte
)

func file_apps_personal_core_adapter_portfolio_proto_rawDescGZIP() []byte {
	file_apps_personal_core_adapter_portfolio_proto_rawDescOnce.Do(func() {
		file_apps_personal_core_adapter_portfolio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_personal_core_adapter_portfolio_proto_rawDesc), len(file_apps_personal_core_adapter_portfolio_proto_rawDesc)))
	})
	return file_apps_personal_core_adapter_portfolio_proto_rawDescData
}

var file_apps_personal_core_adapter_portfolio_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_apps_personal_core_adapter_portfolio_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_apps_personal_core_adapter_portfolio_proto_goTypes = []any{
	(PositionType)(0),             // 0: personal.core.PositionType
	(TradeType)(0),                // 1: personal.core.TradeType
	(*Position)(nil),              // 2: personal.core.Position
	(*Trade)(nil),                 // 3: personal.core.Trade
	(*ValueSnapshot)(nil),         // 4: personal.core.ValueSnapshot
	(*PortfolioConfig)(nil),       // 5: personal.core.PortfolioConfig
	(*ListPositionsResponse)(nil), // 6: personal.core.ListPositionsResponse
	(*CreatePositionRequest)(nil), // 7: personal.core.CreatePositionRequest
	(*UpdatePositionRequest)(nil), // 8: personal.core.UpdatePositionRequest
	(*DeletePositionRequest)(nil), // 9: personal.core.DeletePositionRequest
	(*ListTradesRequest)(nil),     // 10: personal.core.ListTradesRequest
	(*ListTradesResponse)(nil),    // 11: personal.core.ListTradesResponse
	(*CreateTradeRequest)(nil),    // 12: personal.core.CreateTradeRequest
	(*UpdateTradeRequest)(nil),    // 13: personal.core.UpdateTradeRequest
	(*DeleteTradeRequest)(nil),    // 14: personal.core.DeleteTradeRequest
	(*ListSnapshotsResponse)(nil), // 15: personal.core.ListSnapshotsResponse
	(*UpsertSnapshotRequest)(nil), // 16: personal.core.UpsertSnapshotRequest
	(*UpdateConfigRequest)(nil),   // 17: personal.core.UpdateConfigRequest
	(*emptypb.Empty)(nil),         // 18: google.protobuf.Empty
}
var file_apps_personal_core_adapter_portfolio_proto_depIdxs = []int32{
	0,  // 0: personal.core.Position.type:type_name -> personal.core.PositionType
	1,  // 1: personal.core.Trade.type:type_name -> personal.core.TradeType
	2,  // 2: personal.core.ListPositionsResponse.positions:type_name -> personal.core.Position
	0,  // 3: personal.core.CreatePositionRequest.type:type_name -> personal.core.PositionType
	0,  // 4: personal.core.UpdatePositionRequest.type:type_name -> personal.core.PositionType
	3,  // 5: personal.core.ListTradesResponse.trades:type_name -> personal.core.Trade
	1,  // 6: personal.core.CreateTradeRequest.type:type_name -> personal.core.TradeType
	1,  // 7: personal.core.UpdateTradeRequest.type:type_name -> personal.core.TradeType
	4,  // 8: personal.core.ListSnapshotsResponse.snapshots:type_name -> personal.core.ValueSnapshot
	18, // 9: personal.core.Portfolio.ListPositions:input_type -> google.protobuf.Empty
	7,  // 10: personal.core.Portfolio.CreatePosition:input_type -> personal.core.CreatePositionRequest
	8,  // 11: personal.core.Portfolio.UpdatePosition:input_type -> personal.core.UpdatePositionRequest
	9,  // 12: personal.core.Portfolio.DeletePosition:input_type -> personal.core.DeletePositionRequest
	10, // 13: personal.core.Portfolio.ListTrades:input_type -> personal.core.ListTradesRequest
	12, // 14: personal.core.Portfolio.CreateTrade:input_type -> personal.core.CreateTradeRequest
	13, // 15: personal.core.Portfolio.UpdateTrade:input_type -> personal.core.UpdateTradeRequest
	14, // 16: personal.core.Portfolio.DeleteTrade:input_type -> personal.core.DeleteTradeRequest
	18, // 17: personal.core.Portfolio.ListSnapshots:input_type -> google.protobuf.Empty
	16, // 18: personal.core.Portfolio.UpsertSnapshot:input_type -> personal.core.UpsertSnapshotRequest
	18, // 19: personal.core.Portfolio.GetConfig:input_type -> google.protobuf.Empty
	17, // 20: personal.core.Portfolio.UpdateConfig:input_type -> personal.core.UpdateConfigRequest
	6,  // 21: personal.core.Portfolio.ListPositions:output_type -> personal.core.ListPositionsResponse
	2,  // 22: personal.core.Portfolio.CreatePosition:output_type -> personal.core.Position
	2,  // 23: personal.core.Portfolio.UpdatePosition:output_type -> personal.core.Position
	18, // 24: personal.core.Portfolio.DeletePosition:output_type -> google.protobuf.Empty
	11, // 25: personal.core.Portfolio.ListTrades:output_type -> personal.core.ListTradesResponse
	3,  // 26: personal.core.Portfolio.CreateTrade:output_type -> personal.core.Trade
	3,  // 27: personal.core.Portfolio.UpdateTrade:output_type -> personal.core.Trade
	18, // 28: personal.core.Portfolio.DeleteTrade:output_type -> google.protobuf.Empty
	15, // 29: personal.core.Portfolio.ListSnapshots:output_type -> personal.core.ListSnapshotsResponse
	4,  // 30: personal.core.Portfolio.UpsertSnapshot:output_type -> personal.core.ValueSnapshot
	5,  // 31: personal.core.Portfolio.GetConfig:output_type -> personal.core.PortfolioConfig
	5,  // 32: personal.core.Portfolio.UpdateConfig:output_type -> personal.core.PortfolioConfig
	21, // [21:33] is the sub-list for method output_type
	9,  // [9:21] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_apps_personal_core_adapter_portfolio_proto_init() }
func file_apps_personal_core_adapter_portfolio_proto_init() {
	if File_apps_personal_core_adapter_portfolio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_personal_core_adapter_portfolio_proto_rawDesc), len(file_apps_personal_core_adapter_portfolio_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_personal_core_adapter_portfolio_proto_goTypes,
		DependencyIndexes: file_apps_personal_core_adapter_portfolio_proto_depIdxs,
		EnumInfos:         file_apps_personal_core_adapter_portfolio_proto_enumTypes,
		MessageInfos:      file_apps_personal_core_adapter_portfolio_proto_msgTypes,
	}.Build()
	File_apps_personal_core_adapter_portfolio_proto = out.File
	file_apps_personal_core_adapter_portfolio_proto_goTypes = nil
	file_apps_personal_core_adapter_portfolio_proto_depIdxs = nil
}
