// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: apps/personal-core/adapter/profile.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProfileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileInfo) Reset() {
	*x = ProfileInfo{}
	mi := &file_apps_personal_core_adapter_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileInfo) ProtoMessage() {}

func (x *ProfileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_core_adapter_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileInfo.ProtoReflect.Descriptor instead.
func (*ProfileInfo) Descriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_profile_proto_rawDescGZIP(), []int{0}
}

func (x *ProfileInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProfileInfo) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ProfileInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ProfileInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ProfileInfo) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *ProfileInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *ProfileInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ProfileInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_apps_personal_core_adapter_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_core_adapter_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_profile_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfileRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Bio           string                 `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_apps_personal_core_adapter_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_core_adapter_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_profile_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProfileRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateProfileRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *ProfileInfo           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_apps_personal_core_adapter_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_core_adapter_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_apps_personal_core_adapter_profile_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProfileResponse) GetProfile() *ProfileInfo {
	if x != nil {
		return x.Profile
	}
	return nil
}

var File_apps_personal_core_adapter_profile_proto protoreflect.FileDescriptor

const file_apps_personal_core_adapter_profile_proto_rawDesc = "" +
	"\n" +
	"(apps/personal-core/adapter/profile.proto\x12\rpersonal.core\"\xdd\x01\n" +
	"\vProfileInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x06 \x01(\tR\tavatarUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"2\n" +
	"\x11GetProfileRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"y\n" +
	"\x14UpdateProfileRequest\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\"M\n" +
	"\x15UpdateProfileResponse\x124\n" +
	"\aprofile\x18\x01 \x01(\v2\x1a.personal.core.ProfileInfoR\aprofile2\xb1\x01\n" +
	"\aProfile\x12J\n" +
	"\n" +
	"GetProfile\x12 .personal.core.GetProfileRequest\x1a\x1a.personal.core.ProfileInfo\x12Z\n" +
	"\rUpdateProfile\x12#.personal.core.UpdateProfileRequest\x1a$.personal.core.UpdateProfileResponseBHZFgithub.com/eviltomorrow/personal-service/apps/personal-core/adapter/pbb\x06proto3"

var (
	file_apps_personal_core_adapter_profile_proto_rawDescOnce sync.Once
	file_apps_personal_core_adapter_profile_proto_rawDescData []byte
)

func file_apps_personal_core_adapter_profile_proto_rawDescGZIP() []byte {
	file_apps_personal_core_adapter_profile_proto_rawDescOnce.Do(func() {
		file_apps_personal_core_adapter_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_personal_core_adapter_profile_proto_rawDesc), len(file_apps_personal_core_adapter_profile_proto_rawDesc)))
	})
	return file_apps_personal_core_adapter_profile_proto_rawDescData
}

var file_apps_personal_core_adapter_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_apps_personal_core_adapter_profile_proto_goTypes = []any{
	(*ProfileInfo)(nil),           // 0: personal.core.ProfileInfo
	(*GetProfileRequest)(nil),     // 1: personal.core.GetProfileRequest
	(*UpdateProfileRequest)(nil),  // 2: personal.core.UpdateProfileRequest
	(*UpdateProfileResponse)(nil), // 3: personal.core.UpdateProfileResponse
}
var file_apps_personal_core_adapter_profile_proto_depIdxs = []int32{
	0, // 0: personal.core.UpdateProfileResponse.profile:type_name -> personal.core.ProfileInfo
	1, // 1: personal.core.Profile.GetProfile:input_type -> personal.core.GetProfileRequest
	2, // 2: personal.core.Profile.UpdateProfile:input_type -> personal.core.UpdateProfileRequest
	0, // 3: personal.core.Profile.GetProfile:output_type -> personal.core.ProfileInfo
	3, // 4: personal.core.Profile.UpdateProfile:output_type -> personal.core.UpdateProfileResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apps_personal_core_adapter_profile_proto_init() }
func file_apps_personal_core_adapter_profile_proto_init() {
	if File_apps_personal_core_adapter_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_personal_core_adapter_profile_proto_rawDesc), len(file_apps_personal_core_adapter_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_personal_core_adapter_profile_proto_goTypes,
		DependencyIndexes: file_apps_personal_core_adapter_profile_proto_depIdxs,
		MessageInfos:      file_apps_personal_core_adapter_profile_proto_msgTypes,
	}.Build()
	File_apps_personal_core_adapter_profile_proto = out.File
	file_apps_personal_core_adapter_profile_proto_goTypes = nil
	file_apps_personal_core_adapter_profile_proto_depIdxs = nil
}
