[log]
level = "warn"

[network]
bind_ip = "0.0.0.0"
bind_port = 8080
access_ip = ""
disable_tls = true

[etcd]
endpoints = ["etcd:2379"]

[opentrace]
enable = false
dsn = ""

[service]
auth_service_target = "etcd:///grpclb/personal-auth"
finance_service_target = "etcd:///grpclb/personal-finance"
signing_key = "sk_c1d8df11cce60aa705ea95ce9310b99a4177d6a4"