// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: apps/personal-auth/adapter/auth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthType int32

const (
	AuthType_AUTH_TYPE_UNSPECIFIED AuthType = 0
	AuthType_AUTH_TYPE_EMAIL       AuthType = 1
	AuthType_AUTH_TYPE_USERNAME    AuthType = 2
	AuthType_AUTH_TYPE_PHONE       AuthType = 3
)

// Enum value maps for AuthType.
var (
	AuthType_name = map[int32]string{
		0: "AUTH_TYPE_UNSPECIFIED",
		1: "AUTH_TYPE_EMAIL",
		2: "AUTH_TYPE_USERNAME",
		3: "AUTH_TYPE_PHONE",
	}
	AuthType_value = map[string]int32{
		"AUTH_TYPE_UNSPECIFIED": 0,
		"AUTH_TYPE_EMAIL":       1,
		"AUTH_TYPE_USERNAME":    2,
		"AUTH_TYPE_PHONE":       3,
	}
)

func (x AuthType) Enum() *AuthType {
	p := new(AuthType)
	*p = x
	return p
}

func (x AuthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthType) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_personal_auth_adapter_auth_proto_enumTypes[0].Descriptor()
}

func (AuthType) Type() protoreflect.EnumType {
	return &file_apps_personal_auth_adapter_auth_proto_enumTypes[0]
}

func (x AuthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthType.Descriptor instead.
func (AuthType) EnumDescriptor() ([]byte, []int) {
	return file_apps_personal_auth_adapter_auth_proto_rawDescGZIP(), []int{0}
}

type UpdateIdentifierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AuthType      AuthType               `protobuf:"varint,2,opt,name=auth_type,json=authType,proto3,enum=personal.auth.AuthType" json:"auth_type,omitempty"`
	NewIdentifier string                 `protobuf:"bytes,3,opt,name=new_identifier,json=newIdentifier,proto3" json:"new_identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIdentifierRequest) Reset() {
	*x = UpdateIdentifierRequest{}
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIdentifierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIdentifierRequest) ProtoMessage() {}

func (x *UpdateIdentifierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIdentifierRequest.ProtoReflect.Descriptor instead.
func (*UpdateIdentifierRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_auth_adapter_auth_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateIdentifierRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UpdateIdentifierRequest) GetAuthType() AuthType {
	if x != nil {
		return x.AuthType
	}
	return AuthType_AUTH_TYPE_UNSPECIFIED
}

func (x *UpdateIdentifierRequest) GetNewIdentifier() string {
	if x != nil {
		return x.NewIdentifier
	}
	return ""
}

type UpdateIdentifierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIdentifierResponse) Reset() {
	*x = UpdateIdentifierResponse{}
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIdentifierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIdentifierResponse) ProtoMessage() {}

func (x *UpdateIdentifierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIdentifierResponse.ProtoReflect.Descriptor instead.
func (*UpdateIdentifierResponse) Descriptor() ([]byte, []int) {
	return file_apps_personal_auth_adapter_auth_proto_rawDescGZIP(), []int{1}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthType      AuthType               `protobuf:"varint,1,opt,name=auth_type,json=authType,proto3,enum=personal.auth.AuthType" json:"auth_type,omitempty"`
	Identifier    string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_auth_adapter_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetAuthType() AuthType {
	if x != nil {
		return x.AuthType
	}
	return AuthType_AUTH_TYPE_UNSPECIFIED
}

func (x *RegisterRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_apps_personal_auth_adapter_auth_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RegisterResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RegisterResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthType      AuthType               `protobuf:"varint,1,opt,name=auth_type,json=authType,proto3,enum=personal.auth.AuthType" json:"auth_type,omitempty"`
	Identifier    string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_auth_adapter_auth_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetAuthType() AuthType {
	if x != nil {
		return x.AuthType
	}
	return AuthType_AUTH_TYPE_UNSPECIFIED
}

func (x *LoginRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *LoginRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_apps_personal_auth_adapter_auth_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_auth_adapter_auth_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_apps_personal_auth_adapter_auth_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type RevokeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_auth_adapter_auth_proto_rawDescGZIP(), []int{8}
}

func (x *RevokeTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RevokeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenResponse) Reset() {
	*x = RevokeTokenResponse{}
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenResponse) ProtoMessage() {}

func (x *RevokeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return file_apps_personal_auth_adapter_auth_proto_rawDescGZIP(), []int{9}
}

type RevokeAllTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAllTokensRequest) Reset() {
	*x = RevokeAllTokensRequest{}
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAllTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAllTokensRequest) ProtoMessage() {}

func (x *RevokeAllTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAllTokensRequest.ProtoReflect.Descriptor instead.
func (*RevokeAllTokensRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_auth_adapter_auth_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeAllTokensRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type RevokeAllTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAllTokensResponse) Reset() {
	*x = RevokeAllTokensResponse{}
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAllTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAllTokensResponse) ProtoMessage() {}

func (x *RevokeAllTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAllTokensResponse.ProtoReflect.Descriptor instead.
func (*RevokeAllTokensResponse) Descriptor() ([]byte, []int) {
	return file_apps_personal_auth_adapter_auth_proto_rawDescGZIP(), []int{11}
}

type UpdatePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OldPassword   string                 `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordRequest) Reset() {
	*x = UpdatePasswordRequest{}
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordRequest) ProtoMessage() {}

func (x *UpdatePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_auth_adapter_auth_proto_rawDescGZIP(), []int{12}
}

func (x *UpdatePasswordRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UpdatePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *UpdatePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type UpdatePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordResponse) Reset() {
	*x = UpdatePasswordResponse{}
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordResponse) ProtoMessage() {}

func (x *UpdatePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordResponse.ProtoReflect.Descriptor instead.
func (*UpdatePasswordResponse) Descriptor() ([]byte, []int) {
	return file_apps_personal_auth_adapter_auth_proto_rawDescGZIP(), []int{13}
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_auth_adapter_auth_proto_rawDescGZIP(), []int{14}
}

func (x *ValidateTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_apps_personal_auth_adapter_auth_proto_rawDescGZIP(), []int{15}
}

func (x *ValidateTokenResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ValidateTokenResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type DeleteAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_apps_personal_auth_adapter_auth_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DeleteAccountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type DeleteAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountResponse) Reset() {
	*x = DeleteAccountResponse{}
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountResponse) ProtoMessage() {}

func (x *DeleteAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_personal_auth_adapter_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return file_apps_personal_auth_adapter_auth_proto_rawDescGZIP(), []int{17}
}

var File_apps_personal_auth_adapter_auth_proto protoreflect.FileDescriptor

const file_apps_personal_auth_adapter_auth_proto_rawDesc = "" +
	"\n" +
	"%apps/personal-auth/adapter/auth.proto\x12\rpersonal.auth\"\x95\x01\n" +
	"\x17UpdateIdentifierRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x124\n" +
	"\tauth_type\x18\x02 \x01(\x0e2\x17.personal.auth.AuthTypeR\bauthType\x12%\n" +
	"\x0enew_identifier\x18\x03 \x01(\tR\rnewIdentifier\"\x1a\n" +
	"\x18UpdateIdentifierResponse\"\x83\x01\n" +
	"\x0fRegisterRequest\x124\n" +
	"\tauth_type\x18\x01 \x01(\x0e2\x17.personal.auth.AuthTypeR\bauthType\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"y\n" +
	"\x10RegisterResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\"\xbe\x01\n" +
	"\fLoginRequest\x124\n" +
	"\tauth_type\x18\x01 \x01(\x0e2\x17.personal.auth.AuthTypeR\bauthType\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\"v\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"}\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\"9\n" +
	"\x12RevokeTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\x15\n" +
	"\x13RevokeTokenResponse\";\n" +
	"\x16RevokeAllTokensRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\x19\n" +
	"\x17RevokeAllTokensResponse\"|\n" +
	"\x15UpdatePasswordRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12!\n" +
	"\fold_password\x18\x02 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"\x18\n" +
	"\x16UpdatePasswordResponse\"9\n" +
	"\x14ValidateTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"J\n" +
	"\x15ValidateTokenResponse\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\"Q\n" +
	"\x14DeleteAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x17\n" +
	"\x15DeleteAccountResponse*g\n" +
	"\bAuthType\x12\x19\n" +
	"\x15AUTH_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fAUTH_TYPE_EMAIL\x10\x01\x12\x16\n" +
	"\x12AUTH_TYPE_USERNAME\x10\x02\x12\x13\n" +
	"\x0fAUTH_TYPE_PHONE\x10\x032\xa4\x06\n" +
	"\x04Auth\x12K\n" +
	"\bRegister\x12\x1e.personal.auth.RegisterRequest\x1a\x1f.personal.auth.RegisterResponse\x12B\n" +
	"\x05Login\x12\x1b.personal.auth.LoginRequest\x1a\x1c.personal.auth.LoginResponse\x12]\n" +
	"\x0eUpdatePassword\x12$.personal.auth.UpdatePasswordRequest\x1a%.personal.auth.UpdatePasswordResponse\x12Z\n" +
	"\rValidateToken\x12#.personal.auth.ValidateTokenRequest\x1a$.personal.auth.ValidateTokenResponse\x12Z\n" +
	"\rDeleteAccount\x12#.personal.auth.DeleteAccountRequest\x1a$.personal.auth.DeleteAccountResponse\x12W\n" +
	"\fRefreshToken\x12\".personal.auth.RefreshTokenRequest\x1a#.personal.auth.RefreshTokenResponse\x12T\n" +
	"\vRevokeToken\x12!.personal.auth.RevokeTokenRequest\x1a\".personal.auth.RevokeTokenResponse\x12`\n" +
	"\x0fRevokeAllTokens\x12%.personal.auth.RevokeAllTokensRequest\x1a&.personal.auth.RevokeAllTokensResponse\x12c\n" +
	"\x10UpdateIdentifier\x12&.personal.auth.UpdateIdentifierRequest\x1a'.personal.auth.UpdateIdentifierResponseBHZFgithub.com/eviltomorrow/personal-service/apps/personal-auth/adapter/pbb\x06proto3"

var (
	file_apps_personal_auth_adapter_auth_proto_rawDescOnce sync.Once
	file_apps_personal_auth_adapter_auth_proto_rawDescData []byte
)

func file_apps_personal_auth_adapter_auth_proto_rawDescGZIP() []byte {
	file_apps_personal_auth_adapter_auth_proto_rawDescOnce.Do(func() {
		file_apps_personal_auth_adapter_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_personal_auth_adapter_auth_proto_rawDesc), len(file_apps_personal_auth_adapter_auth_proto_rawDesc)))
	})
	return file_apps_personal_auth_adapter_auth_proto_rawDescData
}

var file_apps_personal_auth_adapter_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_apps_personal_auth_adapter_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_apps_personal_auth_adapter_auth_proto_goTypes = []any{
	(AuthType)(0),                    // 0: personal.auth.AuthType
	(*UpdateIdentifierRequest)(nil),  // 1: personal.auth.UpdateIdentifierRequest
	(*UpdateIdentifierResponse)(nil), // 2: personal.auth.UpdateIdentifierResponse
	(*RegisterRequest)(nil),          // 3: personal.auth.RegisterRequest
	(*RegisterResponse)(nil),         // 4: personal.auth.RegisterResponse
	(*LoginRequest)(nil),             // 5: personal.auth.LoginRequest
	(*LoginResponse)(nil),            // 6: personal.auth.LoginResponse
	(*RefreshTokenRequest)(nil),      // 7: personal.auth.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),     // 8: personal.auth.RefreshTokenResponse
	(*RevokeTokenRequest)(nil),       // 9: personal.auth.RevokeTokenRequest
	(*RevokeTokenResponse)(nil),      // 10: personal.auth.RevokeTokenResponse
	(*RevokeAllTokensRequest)(nil),   // 11: personal.auth.RevokeAllTokensRequest
	(*RevokeAllTokensResponse)(nil),  // 12: personal.auth.RevokeAllTokensResponse
	(*UpdatePasswordRequest)(nil),    // 13: personal.auth.UpdatePasswordRequest
	(*UpdatePasswordResponse)(nil),   // 14: personal.auth.UpdatePasswordResponse
	(*ValidateTokenRequest)(nil),     // 15: personal.auth.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),    // 16: personal.auth.ValidateTokenResponse
	(*DeleteAccountRequest)(nil),     // 17: personal.auth.DeleteAccountRequest
	(*DeleteAccountResponse)(nil),    // 18: personal.auth.DeleteAccountResponse
}
var file_apps_personal_auth_adapter_auth_proto_depIdxs = []int32{
	0,  // 0: personal.auth.UpdateIdentifierRequest.auth_type:type_name -> personal.auth.AuthType
	0,  // 1: personal.auth.RegisterRequest.auth_type:type_name -> personal.auth.AuthType
	0,  // 2: personal.auth.LoginRequest.auth_type:type_name -> personal.auth.AuthType
	3,  // 3: personal.auth.Auth.Register:input_type -> personal.auth.RegisterRequest
	5,  // 4: personal.auth.Auth.Login:input_type -> personal.auth.LoginRequest
	13, // 5: personal.auth.Auth.UpdatePassword:input_type -> personal.auth.UpdatePasswordRequest
	15, // 6: personal.auth.Auth.ValidateToken:input_type -> personal.auth.ValidateTokenRequest
	17, // 7: personal.auth.Auth.DeleteAccount:input_type -> personal.auth.DeleteAccountRequest
	7,  // 8: personal.auth.Auth.RefreshToken:input_type -> personal.auth.RefreshTokenRequest
	9,  // 9: personal.auth.Auth.RevokeToken:input_type -> personal.auth.RevokeTokenRequest
	11, // 10: personal.auth.Auth.RevokeAllTokens:input_type -> personal.auth.RevokeAllTokensRequest
	1,  // 11: personal.auth.Auth.UpdateIdentifier:input_type -> personal.auth.UpdateIdentifierRequest
	4,  // 12: personal.auth.Auth.Register:output_type -> personal.auth.RegisterResponse
	6,  // 13: personal.auth.Auth.Login:output_type -> personal.auth.LoginResponse
	14, // 14: personal.auth.Auth.UpdatePassword:output_type -> personal.auth.UpdatePasswordResponse
	16, // 15: personal.auth.Auth.ValidateToken:output_type -> personal.auth.ValidateTokenResponse
	18, // 16: personal.auth.Auth.DeleteAccount:output_type -> personal.auth.DeleteAccountResponse
	8,  // 17: personal.auth.Auth.RefreshToken:output_type -> personal.auth.RefreshTokenResponse
	10, // 18: personal.auth.Auth.RevokeToken:output_type -> personal.auth.RevokeTokenResponse
	12, // 19: personal.auth.Auth.RevokeAllTokens:output_type -> personal.auth.RevokeAllTokensResponse
	2,  // 20: personal.auth.Auth.UpdateIdentifier:output_type -> personal.auth.UpdateIdentifierResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_apps_personal_auth_adapter_auth_proto_init() }
func file_apps_personal_auth_adapter_auth_proto_init() {
	if File_apps_personal_auth_adapter_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_personal_auth_adapter_auth_proto_rawDesc), len(file_apps_personal_auth_adapter_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_personal_auth_adapter_auth_proto_goTypes,
		DependencyIndexes: file_apps_personal_auth_adapter_auth_proto_depIdxs,
		EnumInfos:         file_apps_personal_auth_adapter_auth_proto_enumTypes,
		MessageInfos:      file_apps_personal_auth_adapter_auth_proto_msgTypes,
	}.Build()
	File_apps_personal_auth_adapter_auth_proto = out.File
	file_apps_personal_auth_adapter_auth_proto_goTypes = nil
	file_apps_personal_auth_adapter_auth_proto_depIdxs = nil
}
