[log]
level = "debug"

[network]
bind_ip = "0.0.0.0"
bind_port = 50002
access_ip = ""
disable_tls = true

[mysql]
dsn = "root:root@tcp(mysql:3306)/personal_core?charset=utf8mb4&parseTime=True&loc=Local"
min_open = 3
max_open = 10

[redis]
dsn = "redis://redis:6379/0"

[etcd]
endpoints = ["etcd:2379"]

[opentrace]
enable = false
dsn = ""
